development:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: fordian

test: &test
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql_ultimate
      database: fedena
      port: 3306
      username: root
      password: foradian
cucumber:
  <<: *test
